### ISSUE TITLE
broken link to pgp key

### ISSUE THREAD

**Issue by layaxx** [ovlb/home-11ty#2]
On your homepage (https://www.ovl.design/) you link to your pgp key (https://www.ovl.design/res/pgpkey-o-at-ovl-design.asc). This gives a 404 however.

**Comment by ovlb** [comment]
Ooopsi. Thanks for letting me know. I’ve fixed this with https://github.com/ovlb/home-11ty/commit/50b10d31a978055fff38c3a985f0ee9af4eac88f.
